### PR TITLE
Fix #197: Take setuid, setgid and sticky bit into account

### LINKED ISSUE #197: permissions 's'/'t' support?
### Description
look's like colorls don't support permissions about 's' and 't'.

For Example:
for ls:
-> ls -l /usr/sbin/passwd 
-rwsr-xr-x 1 root root 55416 Dec 17  2017 /usr/sbin/passwd

for colorls:
-> colorls -l /usr/sbin/passwd 
  rwxr-xr-x    root   54 KiB  Sun Dec 17 00:03:57 2017    passwd 

i got the wrong 'x' insted of 's'.

- Type of issue :
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality

### PR DESCRIPTION
**Pull request by avdv**
### Description

This PR changes the output of file permissions to correctly show permissions if a special bit is set.

- Relevant Issues : #197
- Relevant PRs : (none)
- Type of change :
  - [ ] New feature
  - [x] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

### CODE REVIEW

File: lib/colorls/core.rb [hunk 1]
```diff
@@ -164,20 +164,29 @@ def display_report
         .colorize(@colors[:report])
     end
 
+    def format_mode(rwx, special, char)
+      r = 'r'.colorize(@colors[:read]).freeze
+      w = 'w'.colorize(@colors[:write]).freeze
+      x = 'x'.colorize(@colors[:exec]).freeze
+      na = '-'.colorize(@colors[:no_access]).freeze
```
Comment (avdv) [inline lib/colorls/core.rb]: Well, I think the `freeze` calls really have no effect here. I wanted to reduce string allocations, but this only works for literals.

How about making these constants attributes of the class? That way they would be only initialized once, not for every single file. What do you think, @athityakumar?
